### ISSUE TITLE
Editare martor form afisand continutul existent in DB

### ISSUE THREAD

**Issue by ionescu77** [Dominiq97/news-website#11]
1. In `views.py`
Cand instantiezi `PostForm()` ii trimiti informatia deja existenta `PostForm(`news.body`)`

```python
def news_edit(request,pk):
    news = News.objects.get(pk=pk)
    category = SubCategory.objects.all()
    form = PostForm(some_body=news.body)
    if request.method == 'POST':
        newstitle = request.POST.get('newstitle')
        newscategory = request.POST.get('newscategory')
        newssummary = request.POST.get('newssummary')
        newsbody = request.POST.get('body')
        newsid = request.POST.get('newscategory')
```

2. In`forms.py`
Faci "override" cand se initializeaza PostForm cu `__init__` si:
- extragi informatia din `views.py` cu `kwargs.pop('some_body', None)`
- apoi daca ai primit informatie setezi form field-ul `body` folosind `.initial`

```python
from django import forms

from martor.fields import MartorFormField
from .models import News


class SimpleForm(forms.Form):
    body = MartorFormField()


class PostForm(forms.ModelForm):
    class Meta:
        model = News
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        # Aici initializam form-ul cu some_body
        # primit din views.py news_edit
        body = kwargs.pop('some_body', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if body:
            self.fields['body'].initial = body

```

**Comment by ionescu77** [comment]
O sa salvez branch-ul meu.

Dar te rog experimenteaza si make it work ca erai aproape.

**Comment by ionescu77** [comment]
M-am inspirat din issue mai vechi la martor, apoi a trebuit sa studiez un pic sa imi amintesc cum poti transmite informatia din view.py catre un forms.py

Practic trebuie sa initializezi formul cu valoarea (cum face martot in admin):

https://github.com/agusmakmun/django-markdown-editor/issues/32

Ceva in genul asta

https://stackoverflow.com/questions/1993014/passing-kwargs-to-django-form

**Comment by Dominiq97** [comment]
https://github.com/Dominiq97/news-website/commit/bd2cb7be2e2faf48c06716e6df4bb9301275220d
Multumesc mult, acum m-am prins cum merge si treaba cu kwargs<br>
Am creat un nou branch Martor-Original **plus ca**<br>
**Se poate face live markdown din editarea setarilor** 
https://github.com/Dominiq97/news-website/commit/a4eb19a15d5451cabe43e89765157cb3f9f14939

Deci o noua modalitate de a avea si markdownX dar mai usor de implementat
