### ISSUE TITLE
Quality check

### ISSUE THREAD

**Issue by ionescu77** [Dominiq97/news-website#8]
Salut,
## overall
- [x] home link nu merge din toate paginile
daca fac click pe home din news detail:
ma trimite la <http://127.0.0.1:8000/news/3/index.html>

- [x] multe broken links

a fost foarte greu.
Am adaugat si reusit sa adaug news fara imagini.
## markdown
Se si afisau dar nu era interpretat markdown-ul. Ma intrebam daca am instalat bine sau daca eram in branch-ul corect.
- In panel aparea markdown la un news mi vechi fara imagine
> (noroc cam tinut minte din webshare ca tu scriai `panel` in url bar in chrome):
<img width="910" alt="Screenshot 2020-06-19 at 15 49 57" src="https://user-images.githubusercontent.com/8016748/85134101-9ffe8800-b244-11ea-96fa-e1f0feffb327.png">

- in home page mergeam la acelasi news la detail si nu se vede markdown
<img width="420" alt="Screenshot 2020-06-19 at 15 49 31" src="https://user-images.githubusercontent.com/8016748/85134163-b86ea280-b244-11ea-8bb0-504e16a76672.png">

Abia cand am stat sa caut o imagine la mine, a inceput sa mearga treaba:
- panel
<img width="1293" alt="Screenshot 2020-06-19 at 15 46 10" src="https://user-images.githubusercontent.com/8016748/85133921-4ac27680-b244-11ea-9348-eee75608c97c.png">

- news detail
<img width="726" alt="Screenshot 2020-06-19 at 15 48 38" src="https://user-images.githubusercontent.com/8016748/85134220-cfad9000-b244-11ea-9ab5-4dfc6c358da3.png">

**Comment by ionescu77** [comment]
Te rog cauta si tu weekendul asta cateva ore sa faci prototipul cat de cat functional.
- sa nu mai fie asa multe broken links
- sa fie un buton pt panel
- sa fie un flow agreabil, pentru ca navigarea face si testarea martor dificila

E dificil ca suntem in `Martor-New` branch unde cred ca am facut si "curatenie" miercuri impreuna.
Dar e pacat tu m-ai obisnuit cu calitate in proiectele tale trecute.

Adica cand faceai un demo mergeau toate link-urile.

Arata tot website-ul mega profi.

Acum o sa facem Martor Markdown field-ul sa mearga (fac un branch nou din acest `Martor-New` si o sa facem merge in `master` cand e stabil.

**Comment by Dominiq97** [comment]
https://github.com/Dominiq97/news-website/commit/bd2cb7be2e2faf48c06716e6df4bb9301275220d
N am prea facut un commit destept aici: implementare de martor corecta cu editare plus 
**link uri din panel in website si invers.. am scris si in documentatie**
Web-site -> in barmeniul din header ul paginii "Admin Panel" button
Panel -> in meniul din stanga "Website" button
https://github.com/Dominiq97/news-website/commit/9dcf5389848cef3478b4f379d54be1f66f015a1e

**Comment by Dominiq97** [comment]
Si am mai eliminat si link-uri care nu s de folos pentru ca n am ajuns inca in partile lor din tutorial. Pe altele le pastrez pt categorii si alte detalii.
