### ISSUE TITLE
Category, sub-category edit lipseste

### ISSUE THREAD

**Issue by ionescu77** [Dominiq97/news-website#9]
Category, sub-category edit lipseste

**Comment by Dominiq97** [comment]
Edit si delete category subcategory adaugate:

**Comment by Dominiq97** [comment]
https://github.com/Dominiq97/news-website/commit/c4fba80c4c051114f1d07f1a7b35765d1e7f246b
https://github.com/Dominiq97/news-website/commit/91915c8917452e61521db8d6b1509db875a28f72
https://github.com/Dominiq97/news-website/commit/53640c5ba731cab00f5a0f14c505dfbcd551f5ad
